### ISSUE TITLE
US 01.03.01 Book status as available, requested, accepted, or borrowed

### ISSUE THREAD

**Issue by mxiuwang** [CMPUT301F20T22/papr-w8#3]
**Feature Number (from eClass)**
US 01.03.01

**Rationale**
As an owner or borrower, I want a book to have a status to be one of: available, requested, accepted, or borrowed so that I can differentiate between the availability of different books.

**Please describe if your feature request is related to a problem, or the reason for this feature request.**

**Additional context**

**Comment by scottkavalinas** [comment]
Owner or Borrower perspective, my_books (#33)
