### ISSUE TITLE
US 01.04.01 view book details

### ISSUE THREAD

**Issue by mxiuwang** [CMPUT301F20T22/papr-w8#4]
**Feature Number (from eClass)**
US 01.04.01

**Rationale (from eClass)**
As an owner, I want to view a list of all my books, and their descriptions, statuses, and current borrowers so that I can keep track of all my books.

**Please describe if your feature request is related to a problem, or the reason for this feature request.**

**Additional context**

**Comment by scottkavalinas** [comment]
Owner perspective,my_books (#33)
