### ISSUE TITLE
US 01.06.01 View and edit Book description

### ISSUE THREAD

**Issue by mxiuwang** [CMPUT301F20T22/papr-w8#6]
**Feature Number (from eClass)**
US 01.06.01

**Rationale**
As an owner, I want to view and edit a book description in my books so that I can keep track of my books and make changes if needed. 

**Please describe if your feature request is related to a problem, or the reason for this feature request.**

**Additional context**

**Comment by scottkavalinas** [comment]
Owner perspective, my_books (#33)
