### ISSUE TITLE
US 01.07.01 Delete book

### ISSUE THREAD

**Issue by mxiuwang** [CMPUT301F20T22/papr-w8#7]
**Feature Number (from eClass)**
Ex. US 01.01.01

**Rationale**
As an owner, I want to delete a book in my books so that I can remove any books I no longer want in my library.

**Please describe if your feature request is related to a problem, or the reason for this feature request.**

**Additional context**

**Comment by scottkavalinas** [comment]
Owner Perspective, deletes item from my books list
